if(NOT DEFINED LEAF_VK_BIN OR NOT EXISTS "${LEAF_VK_BIN}")
    message(FATAL_ERROR "LEAF_VK_BIN is missing: ${LEAF_VK_BIN}")
endif()
if(NOT DEFINED AGG_VK_BIN OR NOT EXISTS "${AGG_VK_BIN}")
    message(FATAL_ERROR "AGG_VK_BIN is missing: ${AGG_VK_BIN}")
endif()
if(NOT DEFINED OUT_HDR)
    message(FATAL_ERROR "OUT_HDR is missing")
endif()

file(READ "${LEAF_VK_BIN}" LEAF_HEX HEX)
file(READ "${AGG_VK_BIN}" AGG_HEX HEX)

string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " LEAF_ARR "${LEAF_HEX}")
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " AGG_ARR "${AGG_HEX}")

file(WRITE "${OUT_HDR}" "#pragma once\n")
file(APPEND "${OUT_HDR}" "#include <cstddef>\n")
file(APPEND "${OUT_HDR}" "#include <cstdint>\n\n")
file(APPEND "${OUT_HDR}" "namespace bb::batch_merge::embedded_vks {\n")
file(APPEND "${OUT_HDR}" "inline constexpr uint8_t BATCH_MERGE_LEAF_VK[] = { ${LEAF_ARR} };\n")
file(APPEND "${OUT_HDR}" "inline constexpr uint8_t BATCH_MERGE_AGG_VK[] = { ${AGG_ARR} };\n")
file(APPEND "${OUT_HDR}" "inline constexpr size_t BATCH_MERGE_LEAF_VK_SIZE = sizeof(BATCH_MERGE_LEAF_VK);\n")
file(APPEND "${OUT_HDR}" "inline constexpr size_t BATCH_MERGE_AGG_VK_SIZE = sizeof(BATCH_MERGE_AGG_VK);\n")
file(APPEND "${OUT_HDR}" "} // namespace bb::batch_merge::embedded_vks\n")
