if(NOT DEFINED LEAF_VK_BIN OR NOT EXISTS "${LEAF_VK_BIN}")
    message(FATAL_ERROR "LEAF_VK_BIN is missing: ${LEAF_VK_BIN}")
endif()
if(NOT DEFINED AGG_VK_BIN OR NOT EXISTS "${AGG_VK_BIN}")
    message(FATAL_ERROR "AGG_VK_BIN is missing: ${AGG_VK_BIN}")
endif()
foreach(ARITY RANGE 3 24)
    set(LEAF_VAR "LEAF_${ARITY}_VK_BIN")
    set(AGG_VAR "AGG_${ARITY}_VK_BIN")
    if(NOT DEFINED ${LEAF_VAR} OR NOT EXISTS "${${LEAF_VAR}}")
        message(FATAL_ERROR "${LEAF_VAR} is missing: ${${LEAF_VAR}}")
    endif()
    if(NOT DEFINED ${AGG_VAR} OR NOT EXISTS "${${AGG_VAR}}")
        message(FATAL_ERROR "${AGG_VAR} is missing: ${${AGG_VAR}}")
    endif()
endforeach()
if(NOT DEFINED OUT_HDR)
    message(FATAL_ERROR "OUT_HDR is missing")
endif()

file(WRITE "${OUT_HDR}" "#pragma once\n")
file(APPEND "${OUT_HDR}" "#include <cstddef>\n")
file(APPEND "${OUT_HDR}" "#include <cstdint>\n\n")
file(APPEND "${OUT_HDR}" "namespace bb::batch_merge::embedded_vks {\n")

foreach(ARITY RANGE 2 24)
    if(ARITY EQUAL 2)
        set(LEAF_PATH "${LEAF_VK_BIN}")
        set(AGG_PATH "${AGG_VK_BIN}")
    else()
        set(LEAF_VAR "LEAF_${ARITY}_VK_BIN")
        set(AGG_VAR "AGG_${ARITY}_VK_BIN")
        set(LEAF_PATH "${${LEAF_VAR}}")
        set(AGG_PATH "${${AGG_VAR}}")
    endif()

    file(READ "${LEAF_PATH}" LEAF_HEX HEX)
    file(READ "${AGG_PATH}" AGG_HEX HEX)
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " LEAF_ARR "${LEAF_HEX}")
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1, " AGG_ARR "${AGG_HEX}")
    file(APPEND "${OUT_HDR}" "inline constexpr uint8_t BATCH_MERGE_LEAF_VK_${ARITY}[] = { ${LEAF_ARR} };\n")
    file(APPEND "${OUT_HDR}" "inline constexpr uint8_t BATCH_MERGE_AGG_VK_${ARITY}[] = { ${AGG_ARR} };\n")
    file(APPEND "${OUT_HDR}" "inline constexpr size_t BATCH_MERGE_LEAF_VK_${ARITY}_SIZE = sizeof(BATCH_MERGE_LEAF_VK_${ARITY});\n")
    file(APPEND "${OUT_HDR}" "inline constexpr size_t BATCH_MERGE_AGG_VK_${ARITY}_SIZE = sizeof(BATCH_MERGE_AGG_VK_${ARITY});\n")
endforeach()

file(APPEND "${OUT_HDR}" "inline constexpr const uint8_t* BATCH_MERGE_LEAF_VK = BATCH_MERGE_LEAF_VK_2;\n")
file(APPEND "${OUT_HDR}" "inline constexpr const uint8_t* BATCH_MERGE_AGG_VK = BATCH_MERGE_AGG_VK_2;\n")
file(APPEND "${OUT_HDR}" "inline constexpr size_t BATCH_MERGE_LEAF_VK_SIZE = BATCH_MERGE_LEAF_VK_2_SIZE;\n")
file(APPEND "${OUT_HDR}" "inline constexpr size_t BATCH_MERGE_AGG_VK_SIZE = BATCH_MERGE_AGG_VK_2_SIZE;\n")
file(APPEND "${OUT_HDR}" "} // namespace bb::batch_merge::embedded_vks\n")
